Name: yh-wxgw

Log:
  Level: debug
  Format: console
  ToFile: true
  Directory: ./logs
  Development: true

Nats:
  Address: nats://172.18.0.194:4222
  Username:
  Password:
  Subscribes:
    - prtg.alert
    - radius.auth.reject

Weixin:
  CorpID: ww11b6163d2ec85e5a
  CorpSecret: gDAcHTPUor4ZrnJcwEVxY1qIK2WFFyMWW3VfsrruQN0
  AgentID: 1000002
  WebhookKey: 7e6dfebc-78ea-4fd7-bb65-d5421f4af66c
  QYAPIHostOverride:
  TLSKeyLogFile: